### ISSUE TITLE
add a specific dictionary blueprint for enums

### ISSUE THREAD

**Issue by JoeGannon** [Construktion/Construktion#16]
As of now dictionaries are created with 4 items. When a dictionary is requested with an enum key and the enum has less than 4 values you'll get stuck in an infinite loop.

**Comment by AzureByte** [comment]
Hi, I would like to help with this. I've set up the project and am running the testcases. Will let you know when I have something.

SideNote:
I was having trouble getting the project open in Visual Studio 2015/MonoDevelop saying "TF400813: Resource not available for anonymous access. Client authentication required."
Going through some other threads with the same issue I installed VS2017 and it seemed to fix it. But thought I'd mention it in case you want to include it in the ReadMe as 'Common Issues'

**Comment by AzureByte** [comment]
@JoeGannon  Have submitted a PR here #31

**Comment by JoeGannon** [comment]
Thanks for the PR @AzureByte. Yeah... sorry about that. I'll add a "Working with the code" section to the readme.
