### ISSUE TITLE
Construktion Context PlaceHolders

### ISSUE THREAD

**Issue by JoeGannon** [Construktion/Construktion#59]
Let's use Nullo's to avoid NRE's when accessing properties on the ConstruktionContext.

**Comment by micheleissa** [comment]
Hi,
I'd like to tackle this one. Could you elaborate more @JoeGannon 

thank you.

**Comment by JoeGannon** [comment]
Hi @micheleissa, thanks for wanting to contribute! Right now there's properties on the  [ConstruktionContext](https://github.com/Construktion/Construktion/blob/master/Construktion/ConstruktionContext.cs) class that can be null, and it's the burden of the client to make sure they aren't null. You can see this reflected on the example blueprint in the readme. My thought was to use a [null object](https://en.wikipedia.org/wiki/Null_object_pattern) instead of leaving them as null.  

I was thinking the null object could look something like this

```c#
public class NulloConstruktion
{
    public string NulloPropertyInfo { get; set; } = "";

    public void NulloParameterInfo(NulloConstruktion nulloParameter) { }
}
```
For example, when the ConstruktionContext represents a property, instead of ParameterInfo being null, it will be set to the parameter of the NulloParameterInfo method above. Vice versa if a ParameterInfo was passed in. 

You'll have to use reflection to get the Property/Parameter info which ideally should only happen once. Without any better ideas at the moment, I'd say you could store the null object values on `private static readonly fields` of the context.

**Comment by micheleissa** [comment]
Thanks for the rapid response. I kinda get it but I don't fully understand the reflection part. Could you gimme an example.

-Michel

**Comment by micheleissa** [comment]
@JoeGannon How would the NRE happens  while you have guards against the ctors params in `ConstruktionContext` ?
From what I see in the code, there is no way for the client to set the properties to null values

**Comment by JoeGannon** [comment]
Below is a failing test that shows the NRE. In this scenario `context.PropertyInfo` is null. The ctor used is essentially `new ConstruktionContext(typeof(bool))` and PropertyInfo and ParameterInfo will both be null. 

```c#
public class ReproTests
{
    public void should_not_throw_NRE()
    {
        var construktion = new Construktion().With(new IsActiveBlueprint());

        Should.NotThrow(() => construktion.Construct<bool>());
    }

    public class IsActiveBlueprint : Blueprint
    {
        public bool Matches(ConstruktionContext context)
        {
            return context.RequestType == typeof(bool) &&
                   context.PropertyInfo.Name == "IsActive";
        }

        public object Construct(ConstruktionContext context, ConstruktionPipeline pipeline)
        {
            return true;
        }
    }
}
```

It's up to you how you want to write the unit tests, you can add new ConstruktionContext tests or extend the 3 that are there now. This is untested, but for example to handle the non null property info scenario you could add 2 new asserts to this test 

```c#
public void should_set_parameter_info()
{
    var parameterInfo = typeof(ConstruktionContextTests)
        .GetMethod(nameof(TestMethod), BindingFlags.NonPublic | BindingFlags.Instance)
        .GetParameters()
        .Single();

    var context = new ConstruktionContext(parameterInfo);

    context.RequestType.ShouldBe(typeof(string));
    context.ParameterInfo.ShouldNotBe(null);
    //the new asserts
    context.PropertyInfo.ShouldNotBe(null);
    context.PropertyInfo.Name.ShouldBe(nameof(NulloConstruktion.NulloPropertyInfo));
}
```

**Comment by micheleissa** [comment]
Thanks for the examples. From my reading of Null Object [pattern](https://en.wikipedia.org/wiki/Null_object_pattern) I don't know how to proceed especially with 'private static readonly fields' of the context part
A key point of the most of the pattern implementations are having an interface which is not the case here. I'm sorry if I'm dragging you down :( I'm still trying to get my head around your idea.

-Michel

**Comment by JoeGannon** [comment]
Don't get too hung up on the implementation details, we can iterate on it later :). To start I would just try to get the above test to pass.

**Comment by micheleissa** [comment]
But `NulloParameterInfo` doesn't return the same type as `PropertyInfo` so how can we assign it from that?

**Comment by JoeGannon** [comment]
For that one you'd create a ParameterInfo object from that method and assign to the `ParameterInfo` property.
